### ISSUE TITLE
Keycloak user storage SPI, not listing users in keycload admin console

### ISSUE THREAD

**Issue by ayoubAnbara** [kyrcha/keycloak-mysql-user-federation#2]
I have created a user storage SPI based on your example, but when I go to the admin console in keycloak, Manage -> Users -> View all users, only internal db users are displayed,

**Comment by kyrcha** [comment]
As mentioned in the [docs](https://www.keycloak.org/docs/latest/server_admin/#searching-for-users):

> This will search just local Keycloak database and not the federated database (ie. LDAP) because some backends like LDAP don’t have a way to page through users. So if you want the users from federated backend to be synced into Keycloak database you need to either:
> - Adjust search criteria. That will sync just the backend users matching the criteria into Keycloak database.
> - Go to User Federation tab and click Sync all users or Sync changed users in the page with your federation provider.

Unfortunately, I have not implemented the synchronization functionality for this plugin like it exists for the native LDAP SPI.

**Comment by Ilayapsv** [comment]
@kyrcha can you please help out to implement the synchronization functionality for this plugin. Since in the User Federation tab, there is no option to "Sync all users" or "Sync changed users" in the page with your federation provider.

Kindly help regarding the same, thank in advance.
